jk_website:
    resource: "@JKWebsiteBundle/Resources/config/routing.yml"
    prefix:   /

jk_common:
    resource: "@JKCommonBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
