parameters:
    jk.website.controller_index.class: JK\WebsiteBundle\Controller\IndexController

services:
    jk.website.controller_index:
        class: %jk.website.controller_index.class%
        lazy: true
        parent: jk.common.controller_abstract
