parameters:
    jk.website.controller.index.class: JK\WebsiteBundle\Controller\IndexController

services:
    jk.common.controller_abstract:
        abstract: true
        calls:
            - [setTemplate, ["@templating"]]

    jk.website.controller_index:
        class: %jk.website.controller.index.class%
        parent: jk.common.controller_abstract
